import { Application, Container, Graphics } from 'pixi.js';
import { CHUNK_SIZE, findPath, key, TILE_SIZE, tileAt, type Tile } from './world';
type Status = (value: string) => void;
export class Game {
  private app = new Application(); private world = new Container(); private actor = new Container(); private marker = new Graphics(); private seed: string; private onStatus: Status; private px = 0; private py = 0; private path: Tile[] = []; private rendered = new Set<string>();
  constructor(private host: HTMLElement, seed: string, onStatus: Status) { this.seed = seed; this.onStatus = onStatus; void this.init(); }
  private async init() {
    await this.app.init({ resizeTo: this.host, background: '#294942', antialias: true, resolution: Math.min(devicePixelRatio, 2) });
    this.host.appendChild(this.app.canvas); this.app.stage.addChild(this.world, this.marker, this.actor); this.buildHero(); this.app.stage.eventMode = 'static'; this.app.stage.hitArea = this.app.screen; this.app.stage.on('pointertap', (event) => this.go(event.global.x, event.global.y)); this.app.ticker.add((ticker) => this.tick(ticker.deltaMS / 1000)); window.addEventListener('resize', this.resize); this.resize();
  }
  private buildHero() { const body = new Graphics().circle(0, 5, 10).fill('#c96a43').circle(0, -7, 8).fill('#e9c18a').moveTo(-7, -10).lineTo(0, -20).lineTo(7, -10).fill('#263542'); this.actor.addChild(body); }
  private go(screenX: number, screenY: number) { const worldX = Math.round((screenX - this.app.screen.width / 2) / TILE_SIZE + this.px); const worldY = Math.round((screenY - this.app.screen.height / 2) / TILE_SIZE + this.py); const target = tileAt(this.seed, worldX, worldY); const start = tileAt(this.seed, Math.round(this.px), Math.round(this.py)); this.path = findPath(this.seed, start, target).slice(0, 120); this.marker.clear(); this.marker.circle(screenX, screenY, 8).fill({ color: this.path.length ? 0xf4c86a : 0xc96855, alpha: .9 }); this.onStatus(this.path.length ? 'Walking' : 'Blocked terrain'); }
  private tick(dt: number) { if (this.path.length) { const target = this.path[0]; const dx = target.x - this.px; const dy = target.y - this.py; const distance = Math.hypot(dx, dy); const amount = dt * 4.2; if (distance <= amount) { this.px = target.x; this.py = target.y; this.path.shift(); } else { this.px += (dx / distance) * amount; this.py += (dy / distance) * amount; } if (!this.path.length) this.onStatus('Exploring the Emberwild'); } this.render(); }
  private render() { const centerX = this.app.screen.width / 2; const centerY = this.app.screen.height / 2; this.world.position.set(centerX - this.px * TILE_SIZE, centerY - this.py * TILE_SIZE); this.actor.position.set(centerX, centerY); const minX = Math.floor(this.px - this.app.screen.width / TILE_SIZE / 2) - TILE_SIZE; const maxX = Math.ceil(this.px + this.app.screen.width / TILE_SIZE / 2) + TILE_SIZE; const minY = Math.floor(this.py - this.app.screen.height / TILE_SIZE / 2) - TILE_SIZE; const maxY = Math.ceil(this.py + this.app.screen.height / TILE_SIZE / 2) + TILE_SIZE; const minChunkX = Math.floor(minX / CHUNK_SIZE), maxChunkX = Math.floor(maxX / CHUNK_SIZE), minChunkY = Math.floor(minY / CHUNK_SIZE), maxChunkY = Math.floor(maxY / CHUNK_SIZE); for (let cy = minChunkY; cy <= maxChunkY; cy++) for (let cx = minChunkX; cx <= maxChunkX; cx++) this.drawChunk(cx, cy); }
  private drawChunk(cx: number, cy: number) { const chunkKey = key(cx, cy); if (this.rendered.has(chunkKey)) return; const container = new Container(); for (let y = 0; y < CHUNK_SIZE; y++) for (let x = 0; x < CHUNK_SIZE; x++) { const tile = tileAt(this.seed, cx * CHUNK_SIZE + x, cy * CHUNK_SIZE + y); const worldX = (cx * CHUNK_SIZE + x) * TILE_SIZE; const worldY = (cy * CHUNK_SIZE + y) * TILE_SIZE; const colors = { 'deep-water': 0x204d68, 'shallow-water': 0x367d8b, shore: 0xb59b6a, plain: 0x496d4f, hill: 0x657552, mountain: 0x59606a, river: 0x3b8da0, 'starter-ground': 0x806d58 }; const biomeAccents = { ocean: 0x2b6070, lake: 0x3a8090, coast: 0xc6af79, grassland: 0x59744f, forest: 0x315541, swamp: 0x4c6650, desert: 0xa88a5d, tundra: 0x84909a, alpine: 0x9aa4aa }; const g = new Graphics().rect(worldX, worldY, TILE_SIZE + 1, TILE_SIZE + 1).fill(colors[tile.terrain]); if (tile.terrain === 'plain' || tile.terrain === 'hill' || tile.terrain === 'starter-ground') g.rect(worldX + 10, worldY + 10, 12, 12).fill({ color: biomeAccents[tile.biome], alpha: 0.18 }); if (tile.hydrology.shoreline && tile.terrain !== 'shore') g.rect(worldX + 2, worldY + 2, TILE_SIZE - 4, 3).fill({ color: biomeAccents[tile.biome], alpha: 0.35 }); if (tile.landmark) g.circle(worldX + 16, worldY + 16, tile.landmark === 'shrine' ? 6 : 8).fill(tile.landmark === 'shrine' ? 0xf4c86a : biomeAccents[tile.biome]); container.addChild(g); } this.world.addChild(container); this.rendered.add(chunkKey); }
  private resize = () => { this.app.stage.hitArea = this.app.screen; this.render(); };
  destroy() { window.removeEventListener('resize', this.resize); this.app.destroy(true, { children: true }); }
}
