export interface PerformanceStageTimings { queueMs: number; terrainMs: number; featureMs: number; serializationMs: number; transferMs: number; sceneMs: number; gpuMs: number; presentationMs: number; }
export interface PerformanceSnapshot extends PerformanceStageTimings { frames: number; frameMs: number; maxFrameMs: number; chunks: number; chunkMs: number; maxChunkMs: number; displayObjects: number; requestToPresent: number[]; p50RequestToPresent: number; p95RequestToPresent: number; maxRequestToPresent: number; transferBytes: number; cacheTier: string; generatedFeatureCounts: Record<string, number>; longestMainThreadTask: number; }

export class PerformanceMonitor {
  private snapshot: PerformanceSnapshot = { frames: 0, frameMs: 0, maxFrameMs: 0, chunks: 0, chunkMs: 0, maxChunkMs: 0, displayObjects: 0, queueMs: 0, terrainMs: 0, featureMs: 0, serializationMs: 0, transferMs: 0, sceneMs: 0, gpuMs: 0, presentationMs: 0, requestToPresent: [], p50RequestToPresent: 0, p95RequestToPresent: 0, maxRequestToPresent: 0, transferBytes: 0, cacheTier: 'none', generatedFeatureCounts: {}, longestMainThreadTask: 0 };
  measureFrame<T>(work: () => T) { const start = performance.now(); const result = work(); this.recordFrame(performance.now() - start); return result; }
  recordFrame(milliseconds: number) { this.snapshot.frames++; this.snapshot.frameMs = milliseconds; this.snapshot.maxFrameMs = Math.max(this.snapshot.maxFrameMs, milliseconds); this.snapshot.longestMainThreadTask = Math.max(this.snapshot.longestMainThreadTask, milliseconds); }
  recordChunk(milliseconds: number) { this.snapshot.chunks++; this.snapshot.chunkMs += milliseconds; this.snapshot.maxChunkMs = Math.max(this.snapshot.maxChunkMs, milliseconds); }
  recordRequest(milliseconds: number, stages: Partial<PerformanceStageTimings> = {}, metadata: { transferBytes?: number; cacheTier?: string; generatedFeatureCounts?: Record<string, number> } = {}) { const values = [...this.snapshot.requestToPresent, milliseconds].slice(-512).sort((a, b) => a - b); this.snapshot.requestToPresent = values; this.snapshot.p50RequestToPresent = values[Math.floor(values.length * .5)] ?? 0; this.snapshot.p95RequestToPresent = values[Math.min(values.length - 1, Math.floor(values.length * .95))] ?? 0; this.snapshot.maxRequestToPresent = values.at(-1) ?? 0; Object.assign(this.snapshot, stages); if (metadata.transferBytes !== undefined) this.snapshot.transferBytes += metadata.transferBytes; if (metadata.cacheTier) this.snapshot.cacheTier = metadata.cacheTier; if (metadata.generatedFeatureCounts) this.snapshot.generatedFeatureCounts = { ...this.snapshot.generatedFeatureCounts, ...metadata.generatedFeatureCounts }; }
  setDisplayObjects(count: number) { this.snapshot.displayObjects = count; }
  read() { return { ...this.snapshot, requestToPresent: [...this.snapshot.requestToPresent], generatedFeatureCounts: { ...this.snapshot.generatedFeatureCounts } }; }
}
